// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthwestV2.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NorthwestV2.Infrastructure.Migrations
{
    [DbContext(typeof(NorthwestContext))]
    [Migration("20260327215051_55i5555nitial")]
    partial class _55i5555nitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.ItemBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CarryValue")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProductionItemBaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ProductionItemBaseId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ItemBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionPoints")
                        .HasColumnType("integer");

                    b.Property<int>("AttackTypes")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerStance")
                        .HasColumnType("integer");

                    b.Property<int>("BaseToughness")
                        .HasColumnType("integer");

                    b.Property<int>("DefensiveCounter")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sanity")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoomEnum")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.NormalItemBase", b =>
                {
                    b.HasBaseType("AetherFire23.ERP.Domain.Entity.ItemBase");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProductionItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimePointsContributions")
                        .HasColumnType("integer");

                    b.HasIndex("ProductionItemId");

                    b.HasDiscriminator().HasValue("NormalItemBase");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Features.Actions.Productions.Core.Entities.ProductionItemBase", b =>
                {
                    b.HasBaseType("AetherFire23.ERP.Domain.Entity.ItemBase");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("ProductionItemBase");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Features.Actions.Productions.SpyglassProduction.Items.UnfinishedSpyglass", b =>
                {
                    b.HasBaseType("AetherFire23.ERP.Domain.Features.Actions.Productions.Core.Entities.ProductionItemBase");

                    b.HasDiscriminator().HasValue("UnfinishedSpyglass");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.ItemBase", b =>
                {
                    b.HasOne("AetherFire23.ERP.Domain.Entity.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId");

                    b.HasOne("AetherFire23.ERP.Domain.Features.Actions.Productions.Core.Entities.ProductionItemBase", null)
                        .WithMany("LockedItems")
                        .HasForeignKey("ProductionItemBaseId");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Player", b =>
                {
                    b.HasOne("AetherFire23.ERP.Domain.Entity.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AetherFire23.ERP.Domain.Entity.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AetherFire23.ERP.Domain.Entity.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AetherFire23.ERP.Domain.Entity.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("AetherFire23.ERP.Domain.Entity.Player", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Inventory");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Room", b =>
                {
                    b.HasOne("AetherFire23.ERP.Domain.Entity.Game", "Game")
                        .WithMany("Rooms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AetherFire23.ERP.Domain.Entity.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AetherFire23.ERP.Domain.Entity.Room", null)
                        .WithMany("AdjacentRooms")
                        .HasForeignKey("RoomId");

                    b.Navigation("Game");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.User", b =>
                {
                    b.HasOne("AetherFire23.ERP.Domain.Entity.Lobby", "Lobby")
                        .WithMany("Users")
                        .HasForeignKey("LobbyId");

                    b.Navigation("Lobby");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.NormalItemBase", b =>
                {
                    b.HasOne("AetherFire23.ERP.Domain.Features.Actions.Productions.Core.Entities.ProductionItemBase", "ProductionItem")
                        .WithMany()
                        .HasForeignKey("ProductionItemId");

                    b.Navigation("ProductionItem");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Game", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Lobby", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.Room", b =>
                {
                    b.Navigation("AdjacentRooms");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Entity.User", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("AetherFire23.ERP.Domain.Features.Actions.Productions.Core.Entities.ProductionItemBase", b =>
                {
                    b.Navigation("LockedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
